config/routes.rb
Rails.application.routes.draw do
  root "widgets#index"

  resources :widgets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

    def index
        @widgets = Widget.all
        @widget = Widget.new
    end

    def create
        @widget = Widget.new(widget_params)

        if @widget.save
            redirect_to root_path(@widget)
        else
            redirect_to 'index'
        end
    end

    def destroy
        @widget = Widget.find params[:id]

        @widget.destroy
        redirect_to root_path
    end

    private
    
        def widget_params 
            params.require(:widget).permit(:description, :quantity)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WackyWidgets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/widgets/index.html.erb
<div class="container">
    <h1 class="jumbotron text-center">Wacky Widgets</h1>
<br />

<% def wacky_widgets %>
    <% if @widgets.count === 0 %>
       <h3 class="text-center">No Widgets Exist</h3>
    <% else %>
    <table>
    <tr>
        <th>Description</th>
        <th>Quantity</th>
        <th>Remove</th>
    </tr>
    <tbody>
        <% @widgets.each do |w| %>
            <tr>
                <td><%= w.description %></td>
                <td><%= w.quantity %></td>
                <td><%= link_to "X", widget_path(w), method: :delete, class: "btn btn-xs btn-danger" %></td> 
            </tr>
    <% end %>
    </tbody>
</table>
    <% end %>
<% end %>
<% wacky_widgets %>

<div class="row">
    <div class="col"
        <hr>
        <h4>Add a New Widget:</h4>
    </div>
    <%= form_for @widget do |w| %>
        <div class="form-group">
                <%= w.label :description %>
                <%= w.text_field :description, { :class => "form-control"} %>
            </div>
            <div class="form-group">
                <%= w.label :quantity %>
                <%= w.number_field :quantity, { :class => "form-control"}%>
            </div>
        <%= w.submit "Add Widget", class: "btn btn-success" %>
    <% end %>
</div>